apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: simplest-py-http
  name: simplest-py-http
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30303
  selector:
    app: simplest-py-http
  type: NodePort