# Default values for pyserv-http.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  type: NodePort
  port: 8080
  protocol: TCP
  targetPort: 8080
  nodePort: 30303

deployment:
  port: 8080