apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: simplest-py-http
  name: simplest-py-http
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }}
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: simplest-py-http
  type: NodePort